version: '3.7'

services:
  # Docker Visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    networks: 
      - cluster
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  # Web App
  web:
    image: oscarcosta/boat-web-app
    networks: 
      - cluster
    ports:
      - 80:3000
    environment:
      - MYSQL_host={{.Node.Hostname}}
      - MYSQL_database=boatdb
      - MYSQL_user=boatuser
      - MYSQL_password=boatpass
      - CSV_filename=data.csv
    command: /bin/bash -c "cd /usr/src/web_app && npm install -y && npm start"
    depends_on:
      - mysql
    deploy:
      replicas: 4

networks:
  cluster:
    external: true # Use a pre-existing network
